name: example
description: A project used to demo the Todo Reporter
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  restro:
    path: ../restro/

dev_dependencies:
  build_runner: 1.0.0
  flutter_test:
    sdk: flutter
  restro_gen:
    path: ../restro_gen/
