targets:
  $default:
    builders:
      restro_gen|todo_reporter:
        enabled: true

builders:
  web_api:
    import: "package:restro_gen/builder.dart"
    builder_factories: ["webApi"]
    build_extensions: {".dart": [".web_api.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  restro_setup:
    import: "package:restro_gen/builder.dart"
    builder_factories: ["restroSetup"]
    build_extensions: {".dart": [".restro_setup.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]