name: restro_gen
description: Generators for Restro
version: 1.0.0
author: Ganesh Poojary <ganesh4212@gmail.com>
homepage: https://github.com/ganesh-4212/restro

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: 1.0.2
  source_gen: 0.9.3
  code_builder: 3.1.3
  restro:
    path: ../restro/
  
dev_dependencies:
  build_test: ^0.10.3
  build_runner: ^1.0.0
  test: ^1.0.0